### PR TITLE
Update translations.json

### PR DESCRIPTION
**Pull request by gottagofaster236**
https://onlinecorrector.com.ua/%D0%B1%D1%96%D0%BB%D1%8C%D1%88-%D0%BD%D1%96%D0%B6-%D0%BF%D0%BE%D0%BD%D0%B0%D0%B4/

### CODE REVIEW

**Comment by gottagofaster236** [comment]
Please merge ASAP @awerks !!!

**Comment by awerks** [comment]
Amazing work. Well done!

**Comment by gottagofaster236** [comment]
Thanks! I learned it all on 𝕏, the truth platform 🚀 🤣

**Comment by awerks** [comment]
I'm glad you found X (Formerly known as Twitter) useful 😆

**Pull request merged**
